### PR TITLE
fix: cleanup tslint build warnings

### LINKED ISSUE #53: Clean up TSLint warning during build
**Describe the bug**
A few lining issues have cropped in involving unused variables. These should be cleaned up

**To Reproduce**
1. Run `yarn dev` in the web directory

**Screenshots**
```
[0] Starting the development server...
[0] 
[0] Compiled with warnings.
[0] 
[0] [eslint] 
[0] src/components/Bid/index.tsx
[0]   Line 78:24:  Array.prototype.map() expects a value to be returned at the end of arrow function  array-callback-return
[0] 
[0] src/components/PlaceholderCard/index.tsx
[0]   Line 1:10:  'Button' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/components/SdlConfiguration/EnvironmentVariable.tsx
[0]   Line 1:29:  'FormikValues' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/components/SdlConfiguration/Ports.tsx
[0]   Line 4:23:  'Grid' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/components/WalletDeployButton/index.tsx
[0]   Line 122:7:  'Recommended' is assigned a value but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/hooks/useAppCache.ts
[0]   Line 1:8:  'React' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/hooks/useWallet.ts
[0]   Line 3:10:  'KeplrWallet' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/index.tsx
[0]   Line 10:10:  'ReactQueryDevtools' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/pages/FeaturedApps.tsx
[0]   Line 11:7:  'LightIcon' is assigned a value but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/pages/PreflightCheck.tsx
[0]   Line 8:41:   'loadActiveCertificate' is defined but never used  @typescript-eslint/no-unused-vars
[0]   Line 13:10:  'getKeplr' is defined but never used               @typescript-eslint/no-unused-vars
[0]   Line 18:17:  'setKeplr' is assigned a value but never used      @typescript-eslint/no-unused-vars
[0] 
[0] src/pages/SelectApp.tsx
[0]   Line 3:18:  'Box' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/pages/UpdateDeployment.tsx
[0]   Line 23:10:  'Manifest' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/style/mui-theme.ts
[0]   Line 1:23:  'PaletteOptions' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] Search for the keywords to learn more about each warning.
[0] To ignore, add // eslint-disable-next-line to the line before.
[0] 
[0] WARNING in [eslint] 
[0] src/components/Bid/index.tsx
[0]   Line 78:24:  Array.prototype.map() expects a value to be returned at the end of arrow function  array-callback-return
[0] 
[0] src/components/PlaceholderCard/index.tsx
[0]   Line 1:10:  'Button' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/components/SdlConfiguration/EnvironmentVariable.tsx
[0]   Line 1:29:  'FormikValues' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/components/SdlConfiguration/Ports.tsx
[0]   Line 4:23:  'Grid' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/components/WalletDeployButton/index.tsx
[0]   Line 122:7:  'Recommended' is assigned a value but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/hooks/useAppCache.ts
[0]   Line 1:8:  'React' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/hooks/useWallet.ts
[0]   Line 3:10:  'KeplrWallet' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/index.tsx
[0]   Line 10:10:  'ReactQueryDevtools' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/pages/FeaturedApps.tsx
[0]   Line 11:7:  'LightIcon' is assigned a value but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/pages/PreflightCheck.tsx
[0]   Line 8:41:   'loadActiveCertificate' is defined but never used  @typescript-eslint/no-unused-vars
[0]   Line 13:10:  'getKeplr' is defined but never used               @typescript-eslint/no-unused-vars
[0]   Line 18:17:  'setKeplr' is assigned a value but never used      @typescript-eslint/no-unused-vars
[0] 
[0] src/pages/SelectApp.tsx
[0]   Line 3:18:  'Box' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/pages/UpdateDeployment.tsx
[0]   Line 23:10:  'Manifest' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] src/style/mui-theme.ts
[0]   Line 1:23:  'PaletteOptions' is defined but never used  @typescript-eslint/no-unused-vars
[0] 
[0] webpack compiled with 1 warning
[0] No issues found.
```

### PR DESCRIPTION
**Pull request by Amit0617**
Removed unnecessary variables and imports
returned null otherwise for the map function however we could also use forEach ig. 
Fixes #53

### CODE REVIEW

**Review by jtary — APPROVED** [review]

**Comment by jtary** [comment]
thanks for the contribution :wave:

**Comment by anilmurty** [comment]
Thanks @Amit0617 - let me figure out the best way to split the bounty among 3 devs (may require me to create a new bounty and have you accept it)

**Comment by anilmurty** [comment]
Thanks @Amit0617 - not sure if you're from replit ot not - if you are: https://replit.com/bounties/@anilmurty/akash-console-improv-2

**Comment by Amit0617** [comment]
Applied there

**Comment by anilmurty** [comment]
Thanks @Amit0617  - application accepted. I'll close and you'll get the award once we test this on our staging server after deploy (should be in a couple days). Sound good?

**Pull request merged**
