### PR TITLE
fix: remove extra border from around new-deployment button

### LINKED ISSUE #71: 2 strokes on button "+ New Deployment"
**Describe the bug**
2 outlines are shown when hovered over button "+ New Deployment". 

**To Reproduce**
1. Go to 'console.akash.network'
2. Hover on button " + New Deployment"

**Expected behavior**
Hover state should have only one stroke - red. without the gray. 

**Screenshots**
Screenshot 2023-03-16 at 12 31 16

**Desktop (please complete the following information):**
 - OS: macos monterey 12.2
 - Browser chrome
 - Version Version 110.0.5481.177 .

### PR DESCRIPTION
**Pull request by shumakmanohar**
Fixed the RED Hover Issue, By adding a new class name  [block_default_hover] in CSS File, 

[REPLIT BOUNTY PARTICIPATION ACCOUNT ](https://replit.com/@shumakmanohar)

1. Added a New CSS class name to maintain, the previous styles of the component, and only just overriding the hover part of the component
2.  Please Ignore the conversion of single quotes to double quotes, it was done by the extension 

fixes #71

### CODE REVIEW

**Comment by jtary** [comment]
Thanks for the contribution 👋

**Comment by anilmurty** [comment]
Thanks @shumakmanohar - let me figure out the best way to split the bounty among 3 devs (may require me to create a new bounty and have you accept it)

**Comment by anilmurty** [comment]
please apply to this https://replit.com/bounties/@anilmurty/akash-console-improv and I'll accept/ pay

**Comment by shumakmanohar** [comment]
> please apply to this https://replit.com/bounties/@anilmurty/akash-console-improv and I'll accept/ pay

applied

**Comment by anilmurty** [comment]
Thanks @shumakmanohar - application accepted. I'll close and you'll get the award once we test this on our staging server after deploy (should be in a couple days). Sound good?

**Comment by anilmurty** [comment]
Hey @shumakmanohar - I'm starting a discord channel to Console OSS devs. This will be used to communicate new tasks, roadmap/ plans and also enable better communication between devs that contribute regularly. If you are interested in being a part of this send me your discord handle to anil [at] akash.network or share it here.

**Comment by shumakmanohar** [comment]
Hey anilmurty ,
Thank you for the reward, yeah loved to be part on your discord channel , 
My discord : Shumak#7789

Ps: sorry for late reply

**Comment by anilmurty** [comment]
hey @shumakmanohar - is this discord handle for the akash discord server? I'm not finding you there.

**Comment by shumakmanohar** [comment]
Could u add me to the discord ? Shumak#7789

**Comment by anilmurty** [comment]
Hey @shumakmanohar have you created a user ID on the Akash discord sever? I am not seeing you there.

**Comment by shumakmanohar** [comment]
could u check again

**Comment by anilmurty** [comment]
added now. 👍🏼

**Pull request merged**
