### PR TITLE
fix: increase height of right panel in deployment details

### LINKED ISSUE #52: Make log window the same size as the side panel
The log window currently starts out really sim and then expands as logs come in, stopping at a (seemingly) random place about 2/3rd of the heigh of the side panel. 

We should update this so that:
1. The log window is fixed width (does not grow as the logs come in)
2. The size should match the size of the side panel

Screen Shot 2023-02-23 at 5 37 07 PM

### PR DESCRIPTION
**Pull request by avikt18**
This PR fixes #52 
[Replic Account](https://replit.com/@avikt)

**Screenshots of solution:**
 
[Screencast from 25-03-23 01:58:42 AM IST.webm](https://user-images.githubusercontent.com/56340999/227641926-cb6b6942-f1ec-43f0-956a-8a53442a5a7d.webm)

fixes #52

### CODE REVIEW

**Comment by avikt18** [comment]
@anilmurty Kindly review the PR.

**Comment by anilmurty** [comment]
Thanks @avikt18 - @jtary will review

**Review by jtary — APPROVED** [review]

**Comment by anilmurty** [comment]
Thanks @avikt18 - let me figure out the best way to split the bounty among 3 devs (may require me to create a new bounty and have you accept it)

**Comment by anilmurty** [comment]
@avikt18 - please apply to this (https://replit.com/bounties/@anilmurty/akash-console-improv-1) and I'll accept/ pay

**Comment by avikt18** [comment]
@anilmurty Applied :+1:

**Comment by anilmurty** [comment]
@avikt18 - I'm starting a discord channel for Console OSS devs. This will be used to communicate new tasks, roadmap/ plans and also enable better communication between devs that contribute regularly. If you are interested in being a part of this send me your discord handle to anil [at] akash.network or share it here.

**Comment by avikt18** [comment]
Sure @anilmurty. Here it is:
4v!#3096

**Comment by anilmurty** [comment]
Is that for the Akash discord server? I can't seem to find you

**Comment by avikt18** [comment]
Yes that's my discord handle for the server

**Pull request merged**
