### PR TITLE
Updated app.css

### PR DESCRIPTION
**Pull request by masterismail**
edited cs code such that Hover state has only one stroke - red. without the gray.

### CODE REVIEW

**Review by sonicx180 — APPROVED** [review]
nice catch!

**Comment by jtary** [comment]
This doesn't achieve the desired effect:

image

The css-group defines more than just the border, so removing the button entirely causes this regression.

**Comment by jtary** [comment]
fixed by #82

**Comment by anilmurty** [comment]
@masterismail - I'm starting a discord channel to Console OSS devs. This will be used to communicate new tasks, roadmap/ plans and also enable better communication between devs that contribute regularly. If you are interested in being a part of this send me your discord handle to anil [at] akash.network or share it here.

**Comment by masterismail** [comment]
sure ,here's my discord handle : masterismail#7041

**Pull request closed without merging**
