### PR TITLE
feat: make main tiles configurable via deploy-templates

### PR DESCRIPTION
**Pull request by kaushik-rishi**
Fixes issue #98 

- [x] change the route to `landing/node-deployment`
- [x] use deploy-templates to get the data of the landing page

https://user-images.githubusercontent.com/52498617/232325459-9b6a863b-0f0e-490e-8bb6-3431d7ddbea7.mp4

[My replit user profile](https://replit.com/@kaushikrishi)

### CODE REVIEW

**Comment by kaushik-rishi** [comment]
@anilmurty can you please review and suggest improvements/changes ?

**Comment by anilmurty** [comment]
Awesome @kaushik-rishi - @jtary should be able to review/ merge this tomorrow if it looks good.

**Comment by anilmurty** [comment]
Please verify an end-to-end deployment with Console (including close deployment) to make sure nothing is broken.

**Comment by kaushik-rishi** [comment]
> Please verify an end-to-end deployment with Console (including close deployment) to make sure nothing is broken. 

Will do early morning once i wake up.

**Comment by anilmurty** [comment]
hey there - just checking in if you have verified a deployment after this change and this is good to review and merge? Thanks

**Comment by kaushik-rishi** [comment]
@anilmurty Need some help regarding verifying the deployment and testing.

**Comment by kaushik-rishi** [comment]
@anilmurty Seems like you've trasnferred me some more AKT for testing purpose. I will check and let you know. 

Is it enough if i just check deploying an Akash RPC node, or should i also test with a custom sdl ?

**Comment by anilmurty** [comment]
even just a tetris deployment (faster than akash rpc node) should be sufficient.

**Comment by kaushik-rishi** [comment]
@anilmurty 

- [x] tested with a mysql custom sdl
- [x] tested with a akash rpc node deployment
- [x] re-check and ensure styling and code quality

Should be good to merge, your take now.

**Comment by anilmurty** [comment]
Awesome. Thanks so much. @jtary - can you please review and merge if OK? (I will too)

**Review by jtary — APPROVED** [review]

**Review by anilmurty — APPROVED** [review]

**Pull request merged**
